config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights
  resources :bookings

  # Defines the root path route ("/")
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
  validates :code, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight, class_name: 'Flight', foreign_key: 'flight_id'
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport", foreign_key: "departure_airport_id"
  belongs_to :arrival_airport, class_name: "Airport", foreign_key: "arrival_airport_id"
  # validates :start, presence: true
  # validates :duration, presence: true
  has_many :bookings

  scope :matching_airports_and_start, ->(departure_airport_id, arrival_airport_id, start) {
    where(departure_airport_id: departure_airport_id, arrival_airport_id: arrival_airport_id, start: start)}
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    params[:tickets].to_i.times{ @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    puts booking_params

    if @booking.save
      @booking.passengers.each { |passenger| PassengerMailer.with(passenger: passenger).confirm_booking.deliver }
      redirect_to flights_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:_destroy, :id, :name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.includes(:departure_airport, :arrival_airport).all
    retrieve_departure_options
    retrieve_arrival_options
    retrieve_start_options
    perform_flight_search if request.query_parameters[:commit]
  end

  private

  def retrieve_departure_options
    @departure_options = @flights.map { |f| [f.departure_airport.code, f.departure_airport.id] }
  end

  def retrieve_arrival_options
    @arrival_options = @flights.map { |f| [f.arrival_airport.code, f.arrival_airport.id] }
  end

  def retrieve_start_options
    @start_options = @flights.map { |f| [f.start.to_fs(:long), f.start] }
  end

  def perform_flight_search
    @query = request.query_parameters[:flight]
    @found_flights = Flight.matching_airports_and_start(
      @query[:departure_airport_id], @query[:arrival_airport_id], @query[:start]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="form">
  <%= form_with model: @booking do |form| %>
    <div>
      <%= form.label :flight, 'Flight ID' %>
      <%= form.text_field :flight, value: @flight.id, readonly: true, disabled: true %>
      <%= form.hidden_field :flight_id, value: @flight.id %>
    </div>
  
    <div>
      <%= form.label :date, 'Date' %>
      <%= form.text_field :date, value: @flight.start, readonly: true, disabled: true %><br>
    </div>
  
    <div>
      <%= form.label :departure_airport, 'Departure Airport' %>
      <%= form.text_field :departure_airport, value: @flight.departure_airport.code, readonly: true, disabled: true %>
    </div>
  
    <div>
      <%= form.label :arrival_airport, 'Arrival Airport' %>
      <%= form.text_field :arrival_airport, value: @flight.arrival_airport.code, readonly: true, disabled: true %><br><br>
    </div>
  
    <div data-controller='passenger'>
      <div data-passenger-target='div'>
        <%= form.fields_for :passengers do |p| %>
          <%= p.label :name %>
          <%= p.text_field :name %>

          <%= p.label :email %>
          <%= p.email_field :email %><br><br>
        <% end %>
      </div>

      <button type='button' data-action='passenger#add'>Add Passenger</button>

      <template data-passenger-target='template'>
        <div class="nested-fields">
          <%= form.fields_for :passengers, Passenger.new, child_index: 'TEMPLATE' do |p| %>
            <%= p.hidden_field :_destroy%>

            <%= p.label :name %>
            <%= p.text_field :name %>

            <%= p.label :email %>
            <%= p.email_field :email %>

            <button  type='button' data-action='passenger#remove'>Remove</button><br><br>
            
          <% end %>
        </div>
      </template>
    </div>

    <%= form.submit %><br>
    
  <% end %>
</div>

app/views/flights/index.html.erb
<div class="img">
  <%= image_tag "travel-by-plane.jpg" %>
  <div>Book your flight today
  </div>
</div>

<%= form_with model: @flights, url: '/flights', method: :get, data: { turbo_frame: "list-flights" } do |form| %>
  <%= form.label :departure_airport_id %>
  <%= form.select :departure_airport_id, @departure_options %>

  <%= form.label :arrival_airport_id %>
  <%= form.select :arrival_airport_id, @arrival_options %>

  <%= form.label :tickets %>
  <%= form.select :tickets, [1,2,3,4] %>

  <%= form.label :start, 'Flight date' %>
  <%= form.select :start, @start_options %>
  
  <%= form.submit 'Search' %>
<% end %>

<%= turbo_frame_tag id='list-flights' do %>
  <% if request.query_parameters[:commit] %>
    <ul>
      <% if @found_flights.empty? %>
        <p>No flights matching your search query</p>
      <% else %>
        <p>Found <%= @found_flights.count %> flight(s)</p>
        <%= form_with url: new_booking_path, method: :get do |f| %>
          <% @found_flights.each do |flight| %>
            <%= f.radio_button :flight_id, flight.id %>
            <%= f.label "flight_#{flight.id}" do %>
              From: <%= flight.departure_airport.code %>
              To: <%= flight.arrival_airport.code %>
              Date: <%= flight.start.to_fs(:long) %>
              Tickets: <%= request.query_parameters[:flight][:tickets] %>
            <% end %>
            <%= f.hidden_field :tickets, value: request.query_parameters[:flight][:tickets] %>
          <% end %>
          <%= f.submit 'Select Flight', data: { turbo_frame: '_top' } %>
        <% end %>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1><%=link_to 'FlyExpress', root_path %></h1>
    </header>
    <%= yield %>
  </body>
</html>